import {NextIntlClientProvider, hasLocale} from 'next-intl';
// import {notFound} from 'next/navigation';
import {routing} from '@/i18n/routing';
import { Metadata } from 'next';
import Header from '@/components/header/Header';
import { ToastContainer } from 'react-toastify';
import Footer from '@/components/Footer';
import "../globals.css";
import NotFoundPage from './not-found';


export const metadata: Metadata = {
  title: "Osama Next App",
  description: "Generated by create next app",
};
 
export default async function LocaleLayout({
  children,
  params
}: {
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}) {
  // Ensure that the incoming `locale` is valid
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    // If not, show a 404 page
    return <NotFoundPage />;
  }
 
  return (
    <html lang={locale} dir={locale === 'ar' ? 'rtl' : 'ltr'}>
      <body>
        <NextIntlClientProvider>
        <Header />
        <ToastContainer
        theme="colored" // ثيم التنبيه
        position="top-center" // مكان ظهور التنبيه
        hideProgressBar={false} // اخفاء شريط التقدم
        // newestOnTop={false} // التنبيهات الجديدة تظهر في الاعلى
        closeOnClick // اغلاق التنبيه عند الضغط عليه
        // rtl={false} // اتجاه التنبيه من اليمين لليسار
        // pauseOnFocusLoss // توقف التنبيه عند فقدان التركيز
        draggable//قابلة لسحب
        pauseOnHover//توقف عند التمرير على الماوس
        // limit={3} عدد التنبيهات المسموح بها في نفس الوقت
        // closeButton={false} زرار اغلاق التنبيه
        />
        <main>
          {children}
        </main>
        <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
/*




*/
